### ISSUE TITLE
Function not found during IR conversion

### ISSUE THREAD

**Issue by montyly** [crytic/slither#776]
On 0x1c6e268be622be1d0b16e7b49ef2fef927b63c95:
```
slither/slithir/operations/library_call.py", line 24, in can_reenter
    return self.function.can_reenter(callstack)
AttributeError: 'NoneType' object has no attribute 'can_reenter'
```

Most likely the IR conversion fails to find the function. It might be related to https://github.com/crytic/slither/issues/774

**Comment by 0xalpharush** [comment]
This seems to work on 0.8.3
