### ISSUE TITLE
Function not found during IR generation

### ISSUE THREAD

**Issue by montyly** [crytic/slither#774]
https://etherscan.io/address/0x660717f9cf0e35cd8a2b53d9ef17de8a936a65f0#code

```
core/cfg/node.py", line 898, in _find_read_write_call
    raise SlitherException(
slither.exceptions.SlitherException: Function not found on TMP_659(None) = HIGH_LEVEL_CALL, dest:TMP_658(None), function:mul, arguments:['_totalComponents']  . Please try compiling with a recent Solidity version. 'NoneType' object has no attribute 'type'
```

**Comment by 0xalpharush** [comment]
This seems to work on 0.8.3
